### ISSUE TITLE
Paper 1.16.4 can not initialize

### ISSUE THREAD

**Issue by FPSUsername** [XxRogerxX-SPMC/PixelMotd#1]
java version "15.0.1" 2020-10-20
Paper 1.16.4 build 346 (27th of December)
PixelMotd version 8.8.6-Alpha2

This is the error I get when starting up the server with the plugin

```
[14:04:37] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing PixelMOTD v8.8.6-Alpha2 (Is it up to date?)
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at dev.mruniverse.pixelmotd.files.spigotControl.callMotds(spigotControl.java:52) ~[?:?]
	at dev.mruniverse.pixelmotd.files.FileManager.getMotdControl(FileManager.java:50) ~[?:?]
	at dev.mruniverse.pixelmotd.files.FileManager.loadConfiguration(FileManager.java:232) ~[?:?]
	at dev.mruniverse.pixelmotd.init.spigotPixelMOTD.onLoad(spigotPixelMOTD.java:20) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[server.jar:git-Paper-346]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[server.jar:git-Paper-346]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[server.jar:git-Paper-346]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[server.jar:git-Paper-346]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by FPSUsername** [comment]
Seems like this isn't the case with 8.8.6-PreAlpha1 and older versions

**Comment by XxRogerxX-SPMC** [comment]
That's because that version only works for BungeeCord and not for Spigot, you can try UnfinishedVersions of the Alpha3
